# For Railway use
spring.application.name=Cinimini
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Database configuration using placeholders
SPRING_DATASOURCE_URL=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
SPRING_DATASOURCE_USERNAME=${PGUSER}
SPRING_DATASOURCE_PASSWORD=${PGPASSWORD}
# Port configuration for Railway
server.port=${SERVER_PORT:8080}


# Multipart handling:
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.resolve-lazily=true

# Tomcat server limits:
server.tomcat.max-swallow-size=50MB
server.tomcat.max-parameter-count=20000
server.tomcat.max-http-form-post-size=100MB

# Logging & Hibernate
spring.jpa.show-sql=true
logging.level.org.springframework.transaction=trace
logging.level.org.springframework.orm.jpa=trace
logging.level.org.hibernate.engine.transaction=trace
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
